### ISSUE TITLE
investigate why odfuzz failes with gevent 1.5.0 and greater

### ISSUE THREAD

**Issue by phanak-sap** [SAP/odfuzz#51]
Followup from issue #48 , see details about errors there.

**Comment by lubosmj** [comment]
It fails because of this:

> Changed in version 1.5a4: Previously there was a backwards compatibility alias gevent.signal, introduced in 1.1b4, that partly shadowed this module, confusing humans and static analysis tools alike. That alias has been removed. (See gevent.signal_handler.)

Take a look at the docs here: http://www.gevent.org/api/gevent.signal.html#gevent.signal.signal.

The dependency is going to be pinned to `1.4.0`, so I think we may close this issue because it is not relevant anymore. What do you think?

**Comment by phanak-sap** [comment]
well pinning to 1.4.0 is a in effect just temporary workaround. We should change odfuzz so it could use newer version of gevent with all its fixes. Or if not possible at current state, re-investigate after better module separation.

So the issue is now not about what is the root cause but code fix.

**Comment by lubosmj** [comment]
I have already created a commit which fixes this issue. There is no need to investigate it again. See https://github.com/SAP/odfuzz/commit/c171d8b288bf4dffeaba9596dc3c88fa55c46097. I mentioned this in the issue https://github.com/SAP/odfuzz/issues/48.

What really needs to be done is to check whether newer versions of gevent affect current behavior of the fuzzer in terms of sending/receiving requests/responses.

**Comment by phanak-sap** [comment]
oh, i see. the call to `signal_handler()` instead of `signal()`

I would - I know, its another work split but that is the point of it all - move this particular fix  under this issue instead of being part of string encoding PR. I could then test it better in isolation and ideally update the gevent to 20.5.0.

The #47 should now not be affected by this problem, since #52 is merged.
